<a href="https://colab.research.google.com/github/dbckz/aoc-2022/blob/main/AOC_day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [92]:
grid = []

with open('input') as f:
  for line in f:
    row = [int(x) for x in line.strip()]
    grid.append(row)

print(np.array(grid))

[[2 2 2 ... 1 1 0]
 [1 2 2 ... 1 1 2]
 [0 1 2 ... 1 0 0]
 ...
 [0 2 0 ... 0 0 1]
 [0 2 1 ... 1 0 0]
 [2 0 1 ... 0 0 1]]


In [108]:
num_rows = len(grid)
num_cols = len(grid[0])

num_outer = (num_cols*num_rows) - ((num_cols - 2) * (num_rows - 2))

print(num_rows)
print(num_cols)
print(num_outer)

99
99
392


In [109]:
class Tree:
  def __init__(self, coords, is_visible, value):
    self.coords = coords
    self.is_visible = is_visible
    self.value = value


In [112]:
trees = []

for i in range(num_rows):
  for j in range(num_cols):
    value = grid[i][j]
    if (i == 0 or j == 0 or i == num_rows - 1 or j == num_cols - 1):
      trees.append(Tree((i,j), True, value))
    else:
      # Check up
      vis_up = True
      for k in range(i):
        if grid[k][j] >= value:
          vis_up = False

      # Check down
      vis_down = True
      for k in [i+1, num_rows-1]:
        if grid[k][j] >= value:
          vis_down = False

      # Check left
      vis_left = True
      for k in range(j):
        if grid[i][k] >= value:
          vis_left = False

      # Check right
      vis_right = True
      for k in [j+1, num_cols-1]:
        if grid[i][k] >= value:
          vis_right = False

      if (vis_up or vis_down or vis_left or vis_right):
        visibility = True
      else:
        visibility = False

      trees.append(Tree((i,j), visibility, value))

print(sum([t.is_visible for t in trees]))

5270


In [106]:
print(list(range(5)))

[0, 1, 2, 3, 4]
