<a href="https://colab.research.google.com/github/dbckz/aoc-2022/blob/main/AOC_day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [191]:
grid = []

with open('input') as f:
  for line in f:
    row = [int(x) for x in line.strip()]
    grid.append(row)

print(np.array(grid))

[[2 2 2 ... 1 1 0]
 [1 2 2 ... 1 1 2]
 [0 1 2 ... 1 0 0]
 ...
 [0 2 0 ... 0 0 1]
 [0 2 1 ... 1 0 0]
 [2 0 1 ... 0 0 1]]


In [192]:
num_rows = len(grid)
num_cols = len(grid[0])

num_outer = (num_cols*num_rows) - ((num_cols - 2) * (num_rows - 2))

print(num_rows)
print(num_cols)
print(num_outer)

99
99
392


In [185]:
class Tree:
  def __init__(self, coords, is_visible, value, score):
    self.coords = coords
    self.is_visible = is_visible
    self.value = value
    self.score = score


In [197]:
trees = []

for i in range(num_rows):
  for j in range(num_cols):
    value = grid[i][j]
    # if (i == 0 or j == 0 or i == num_rows - 1 or j == num_cols - 1):
      # trees.append(Tree((i,j), True, value, 0))
    # else:
    # Check up
    vis_up = True
    up_marker_distance = 1000
    up_marker_value = 0
    for k in range(i):
      if grid[k][j] >= value:
        dist = abs(i - k)
        if (dist < up_marker_distance):
          up_marker_distance = dist
          up_marker_value = grid[k][j]
        vis_up = False

    # Check down
    vis_down = True
    down_marker_distance = num_rows - i - 1
    for k in range(i+1, num_rows):
      if grid[k][j] >= value:
        if abs(i-k) < down_marker_distance:
          down_marker_distance = abs(i - k)
        vis_down = False

    # Check left
    vis_left = True
    left_marker_distance = 1000
    left_marker_value = 0
    for k in range(j):
      if grid[i][k] >= value:
        dist = abs(j - k)
        if (dist < left_marker_distance):
          left_marker_distance = dist
          left_marker_value = grid[i][k]
        vis_left = False

    # Check right
    vis_right = True
    right_marker_distance = num_cols - j - 1
    for k in range(j+1, num_cols):
      if grid[i][k] >= value:
        if abs(j-k) < right_marker_distance:
          right_marker_distance = abs(j - k)
        vis_right = False

    if (i == 0 or j == 0 or i == num_rows - 1 or j == num_cols - 1):
      visibility = True
    elif (vis_up or vis_down or vis_left or vis_right):
      visibility = True
    else:
      visibility = False

    if up_marker_distance == 1000:
      up_marker_distance = i

    if left_marker_distance == 1000:
      left_marker_distance = j

    score = left_marker_distance * right_marker_distance * up_marker_distance * down_marker_distance

    trees.append(Tree((i,j), visibility, value, score))

print(sum([t.is_visible for t in trees]))
print(max([t.score for t in trees]))

1835
263670
